# Generated by Django 4.2.4 on 2023-08-31 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("post", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Username",
            ),
        ),
        migrations.AddField(
            model_name="fly",
            name="fly_type_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="post.flytype",
                verbose_name="Fly Type",
            ),
        ),
    ]
