# Generated by Django 4.2.4 on 2023-09-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="posttag",
            options={"verbose_name_plural": "Post Tags"},
        ),
        migrations.AddField(
            model_name="fly",
            name="mat_amount",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Amount of materials"
            ),
        ),
        migrations.AddField(
            model_name="fly",
            name="upload",
            field=models.ImageField(
                blank=True, null=True, upload_to=None, verbose_name="Image upload"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(to="post.tag", verbose_name="Tags"),
        ),
        migrations.AlterField(
            model_name="posttype",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
