# Generated by Django 4.2.4 on 2023-09-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_post_upload_alter_fly_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fly",
            name="upload",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/fly_img_dir",
                verbose_name="Image upload",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="upload",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/post_img_dir",
                verbose_name="Image upload",
            ),
        ),
        migrations.DeleteModel(
            name="PostTag",
        ),
    ]
